STYLES = {
    "product-minimal": {
        "label": "Product Minimal",
        "app_bg": "#f7f7fb",
        "canvas_bg": "#fcfcff",
        "topbar_bg": "#ffffff",
        "sidebar_bg": "#ffffff",
        "footer_bg": "#ffffff",
        "text": "#17233a",
        "muted": "#6b768f",
        "border": "#e2e7f0",
        "grid": "#edf1f6",
        "shadow": "shadow-soft",
        "accent": "#3a67ff",
        "accent_soft": "#e8efff",
        "success": "#1f9b74",
        "success_soft": "#e7f6f1",
        "warning": "#d57a28",
        "warning_soft": "#fff0e4",
        "danger": "#d45757",
        "danger_soft": "#fee8e8",
        "purple": "#7e5bef",
        "purple_soft": "#f0ebff",
        "orange": "#ea7b2c",
        "orange_soft": "#fff0e3",
        "teal": "#1186a1",
        "teal_soft": "#e5f7fb",
        "node_bg": "#ffffff",
        "group_alpha": 0.42,
        "lane_alpha": 0.24,
        "title_font": "Inter, Segoe UI Variable Display, Segoe UI, Arial, sans-serif",
        "heading_font": "Inter, Segoe UI Variable Display, Segoe UI, Arial, sans-serif",
    },
    "editorial-technical": {
        "label": "Editorial Technical",
        "app_bg": "#f2efe9",
        "canvas_bg": "#f7f3ed",
        "topbar_bg": "#f5f1ea",
        "sidebar_bg": "#f3eee6",
        "footer_bg": "#f5f1ea",
        "text": "#27231f",
        "muted": "#655d55",
        "border": "#d8cec0",
        "grid": "#e6ddd2",
        "shadow": "shadow-none",
        "accent": "#c48a2a",
        "accent_soft": "#f5ead0",
        "success": "#608e52",
        "success_soft": "#e6efe2",
        "warning": "#c48a2a",
        "warning_soft": "#f7edd8",
        "danger": "#c75b52",
        "danger_soft": "#f7e1df",
        "purple": "#9271b1",
        "purple_soft": "#ece5f3",
        "orange": "#d0864d",
        "orange_soft": "#fae8da",
        "teal": "#5d938c",
        "teal_soft": "#dfeeea",
        "node_bg": "#fbf8f3",
        "group_alpha": 0.55,
        "lane_alpha": 0.28,
        "title_font": "Georgia, Iowan Old Style, Times New Roman, serif",
        "heading_font": "Georgia, Iowan Old Style, Times New Roman, serif",
    },
    "operator-dark": {
        "label": "Operator Dark",
        "app_bg": "#081120",
        "canvas_bg": "#0b1322",
        "topbar_bg": "#0b1220",
        "sidebar_bg": "#0a111d",
        "footer_bg": "#0b1220",
        "text": "#edf2ff",
        "muted": "#95a3c2",
        "border": "#24324a",
        "grid": "#132038",
        "shadow": "shadow-dark",
        "accent": "#5aa1ff",
        "accent_soft": "#12294b",
        "success": "#22c55e",
        "success_soft": "#0f271b",
        "warning": "#f59e0b",
        "warning_soft": "#372400",
        "danger": "#ef4444",
        "danger_soft": "#3a1115",
        "purple": "#8b5cf6",
        "purple_soft": "#251840",
        "orange": "#fb923c",
        "orange_soft": "#33200f",
        "teal": "#14b8a6",
        "teal_soft": "#11302d",
        "node_bg": "#0f1a2d",
        "group_alpha": 0.42,
        "lane_alpha": 0.2,
        "title_font": "Inter, Segoe UI, Arial, sans-serif",
        "heading_font": "Inter, Segoe UI, Arial, sans-serif",
    },
    "neo-depth": {
        "label": "Neo Depth",
        "app_bg": "#eef3f9",
        "canvas_bg": "#f8fbff",
        "topbar_bg": "#ffffff",
        "sidebar_bg": "#fbfdff",
        "footer_bg": "#ffffff",
        "text": "#1e2a3a",
        "muted": "#6b7b90",
        "border": "#dbe5f0",
        "grid": "#edf3fa",
        "shadow": "shadow-depth",
        "accent": "#2d72ff",
        "accent_soft": "#dce8ff",
        "success": "#28a86b",
        "success_soft": "#dcf5e6",
        "warning": "#f2a31b",
        "warning_soft": "#fff1d8",
        "danger": "#ef5350",
        "danger_soft": "#fee2e2",
        "purple": "#845ef7",
        "purple_soft": "#ece7ff",
        "orange": "#f97316",
        "orange_soft": "#ffead9",
        "teal": "#0aa39a",
        "teal_soft": "#dcf8f5",
        "node_bg": "#ffffff",
        "group_alpha": 0.68,
        "lane_alpha": 0.34,
        "title_font": "Inter, Segoe UI, Arial, sans-serif",
        "heading_font": "Iowan Old Style, Georgia, Times New Roman, serif",
    },
}

TONE_KEYS = {
    "accent": ("accent", "accent_soft"),
    "success": ("success", "success_soft"),
    "warning": ("warning", "warning_soft"),
    "danger": ("danger", "danger_soft"),
    "purple": ("purple", "purple_soft"),
    "orange": ("orange", "orange_soft"),
    "teal": ("teal", "teal_soft"),
    "neutral": ("border", "node_bg"),
}
